---
- name: apt update & upgrade
  become: True
  apt:
    upgrade: yes
    update_cache: yes

- name: Install apt packages
  become: True
  apt:
    name:
      - vim
      - zsh
      - git
      - aptitude
      - gdebi
      - build-essential
      - python3
      - python-pip
      - python3-venv

- name: Clone dotfiles
  git:
    repo: "https://github.com/mdan16/dotfiles.git"
    dest: ~/dotfiles
    
- name: Setup dotfiles
  shell: ~/dotfiles/init.sh
